apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-influxdb-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  influxdb2-admin-username: {{ .Files.Get "files/secrets/influxdb2/influxdb2-admin-username" | b64enc | quote }}
  influxdb2-admin-password: {{ .Files.Get "files/secrets/influxdb2/influxdb2-admin-password" | b64enc | quote }}
  influxdb2-admin-token: {{ .Files.Get "files/secrets/influxdb2/influxdb2-admin-token" | b64enc | quote }}
