apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-scene-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  scenescape-ca.pem: {{ .Files.Get "files/secrets/certs/scenescape-ca.pem" | b64enc }}
  controller.auth: {{ .Files.Get "files/secrets/controller.auth" | b64enc }}
  secrets.py: {{ .Files.Get "files/secrets/django/secrets.py" | b64enc }}
