apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-scene
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-scene
spec:
  type: {{ .Values.scene.service.type }}
  ports:
  - port: {{ .Values.scene.service.port }}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}-scene
