apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pgserver
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-pgserver
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-pgserver
