# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "app.fullname" . }}-pdb
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ include "app.fullname" . }}
