# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "app.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.global.appNodePort }}
      {{- end }}
      protocol: TCP
