# Copyright (C) 2026-2027 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

[program:qmmd]
command=qmmd -p 9274
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=30

