# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
{{- if .Values.global.huggingfaceToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-hf-token
  labels:
    {{- include "ovms.labels" . | nindent 4 }}
    app.kubernetes.io/component: inference
type: Opaque
stringData:
  hf-token: {{ .Values.global.huggingfaceToken | quote }}
{{- end }}
