#!/bin/sh
# postinst script
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
	chmod o+w -R /opt/ros/humble/share/pyrealsense2-ai-demo/
	;;

    abort-upgrade|abort-remove|abort-deconfigure)
	;;

    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
	;;
esac

exit 0
