apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-grafana-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  influxdb2-admin-token: {{ .Files.Get "files/secrets/influxdb2/influxdb2-admin-token" | b64enc | quote }}
