{{- if .Values.storage.pv.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-dlstreamer-pipeline-server-videos-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/dlstreamer-pipeline-server-videos
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-dlstreamer-pipeline-server-models-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/dlstreamer-pipeline-server-models
{{- end }}
