# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: ${PROJECT_NAME:-live-video-caption-rag}

services:
  live-video-captioning-rag:
    image: ${REGISTRY:-}live-video-captioning-rag:${TAG:-latest}
    build:
      context: ./app
      args:
        COPYLEFT_SOURCES: ${COPYLEFT_SOURCES:-false}
    container_name: live-video-captioning-rag
    environment:
      http_proxy: ${http_proxy}
      HTTP_PROXY: ${http_proxy}
      https_proxy: ${https_proxy}
      HTTPS_PROXY: ${https_proxy}
      no_proxy: localhost,127.0.0.1,multimodal-embedding-serving,vdms-vector-db,live-video-captioning-rag,${no_proxy}
      NO_PROXY: localhost,127.0.0.1,multimodal-embedding-serving,vdms-vector-db,live-video-captioning-rag,${NO_PROXY}
      LLM_MODEL_ID: ${LLM_MODEL_ID}
      LLM_DEVICE: ${LLM_DEVICE}
      MAX_TOKENS: ${MAX_TOKENS:-1024}
      TOP_K: ${TOP_K:-1}
      SCORE_THRESHOLD: ${SCORE_THRESHOLD:-0.3}
      # EMBEDDING
      EMBEDDING_MODEL: ${EMBEDDING_MODEL_NAME}
      EMBEDDING_HOST: ${EMBEDDING_HOST}
      EMBEDDING_HOST_PORT: ${EMBEDDING_HOST_PORT:-8000}
      # VDMS
      VDMS_HOST: ${VDMS_HOST}
      VDMS_PORT: ${VDMS_PORT:-55555}
    ports:
      - 4172:4172
    devices:
      - "/dev/dri:/dev/dri"
    group_add:
      - ${USER_GROUP_ID-1000}
      # render group ID for ubuntu 20.04 host OS
      - "109"
      # render group ID for ubuntu 22.04 host OS
      - "110"
      # render group ID for ubuntu 24.04 host OS
      - "992"
    volumes:
      - "${MODEL_CACHE_PATH}:/tmp/model_cache"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4172/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - rag_network

  multimodal-embedding-serving:
    image: intel/multimodal-embedding-serving:1.3.4-rc1
    container_name: multimodal-embedding-serving
    ports:
      - '${EMBEDDING_SERVER_PORT:-9777}:8000'
    ipc: host
    environment:
      no_proxy: localhost,127.0.0.1,multimodal-embedding-serving,vdms-vector-db,live-video-captioning-rag,${no_proxy}
      no_proxy_env: localhost,127.0.0.1,vdms-vector-db,multimodal-embedding-serving,live-vide-captioning-rag,${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      EMBEDDING_MODEL_NAME: ${EMBEDDING_MODEL_NAME}
      EMBEDDING_DEVICE: ${EMBEDDING_DEVICE}
      EMBEDDING_USE_OV: ${EMBEDDING_USE_OV}
      EMBEDDING_OV_MODELS_DIR: ${EMBEDDING_OV_MODELS_DIR:-/app/ov_models}
      DEFAULT_START_OFFSET_SEC: ${DEFAULT_START_OFFSET_SEC:-0}
      DEFAULT_CLIP_DURATION: ${DEFAULT_CLIP_DURATION:--1}
      DEFAULT_NUM_FRAMES: ${DEFAULT_NUM_FRAMES:-64}
      OV_PERFORMANCE_MODE: ${OV_PERFORMANCE_MODE:-LATENCY}
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - ${USER_GROUP_ID:-1000}
      - ${VIDEO_GROUP_ID:-44}
      - ${RENDER_GROUP_ID:-1002}
    restart: unless-stopped
    healthcheck:
      test: [ 'CMD-SHELL', 'curl -f http://localhost:8000/health || exit 1' ]
      interval: 10s
      timeout: 10s
      retries: 40
      start_period: 5s
    networks:
      - rag_network
    volumes:
      - ov-models:/home/appuser/.cache/huggingface
      #- data-prep:/tmp/dataprep
      - ov-models:${EMBEDDING_OV_MODELS_DIR:-/app/ov_models}

  vdms-vector-db:
    image: intellabs/vdms:v2.11.0
    container_name: vdms-vector-db
    ipc: host
    environment:
      - no_proxy=localhost,127.0.0.1,multimodal-embedding-serving,vdms-vector-db,live-video-captioning-rag,${no_proxy}
      - no_proxy_env=localhost,127.0.0.1,vdms-vector-db,multimodal-embedding-serving,live-video-captioning-rag,${no_proxy}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - OVERRIDE_db_root_path=/db
      - OVERRIDE_images_path=/db/images
      - OVERRIDE_descriptors_path=/db/descriptors
      - OVERRIDE_blobs_path=/db/blobs
      - OVERRIDE_pmgd_path=/db/graph
    ports:
      - '${VDMS_VDB_HOST_PORT}:55555'
    volumes:
      - vdms-db:/db
    networks:
      - rag_network

volumes:
  ov-models:
    driver: local
  vdms-db:
    driver: local

networks:
  rag_network:
    driver: bridge
