apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-web-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  scenescape-ca.pem: {{ .Files.Get "files/secrets/certs/scenescape-ca.pem" | b64enc }}
  scenescape-web.crt: {{ .Files.Get "files/secrets/certs/scenescape-web.crt" | b64enc }}
  scenescape-web.key: {{ .Files.Get "files/secrets/certs/scenescape-web.key" | b64enc }}
  controller.auth: {{ .Files.Get "files/secrets/controller.auth" | b64enc }}
  browser.auth: {{ .Files.Get "files/secrets/browser.auth" | b64enc }}
  secrets.py: {{ .Files.Get "files/secrets/django/secrets.py" | b64enc }}
