/**
 * DOM renderers for conversation list and messages
 */
const ChatRenderer = (function () {
    let els = null;

    /*
     * Attaches DOM element references for rendering
     */
    function attach(_els) {
        els = _els;
    }

    /*
     * Shows/hides new chat button based on conversation count and previous visibility
     */
    function updateNewChatButtonVisibility() {
        if (!els?.newChatBtn) return;
        const state = ConversationState.getState();
        const everShown = els.newChatBtn.dataset.everShown === '1';

        if (state.conversations.length > 0) {
            els.newChatBtn.hidden = false;
            els.newChatBtn.dataset.everShown = '1';
        } else {
            els.newChatBtn.hidden = everShown ? false : true;
        }
    }

    /*
     * Renders the complete conversation list with titles and delete buttons
     */
    function renderConvList() {
        if (!els?.convList) return;
        const { conversations, activeId } = ConversationState.getState();

        els.convList.innerHTML = '';
        for (const c of conversations) {
            const li = document.createElement('li');
            li.className = 'conv-item' + (c.id === activeId ? ' active' : '');
            li.dataset.id = c.id;

            const title = document.createElement('span');
            title.className = 'conv-title';
            title.textContent = c.title;

            const actions = document.createElement('div');
            actions.className = 'conv-actions';

            const delBtn = document.createElement('button');
            delBtn.className = 'icon-btn-ghost delete-chat';
            delBtn.type = 'button';
            delBtn.title = 'Delete conversation';
            delBtn.setAttribute('aria-label', 'Delete conversation');
            delBtn.innerHTML = `
      <svg viewBox="0 0 24 24" aria-hidden="true" focusable="false">
        <path d="M9 3h6l1 2h4v2H4V5h4l1-2Zm1 6h2v8h-2V9Zm4 0h2v8h-2V9ZM7 9h2v8H7V9Z"
              fill="currentColor"/>
      </svg>
    `;

            actions.appendChild(delBtn);
            li.appendChild(title);
            li.appendChild(actions);
            els.convList.appendChild(li);
        }

        updateNewChatButtonVisibility();
    }

    /*
     * Renders all messages for a specific conversation including frames metadata
     */
    function renderConversation(id) {
        const { conversations } = ConversationState.getState();
        const conv = conversations.find(c => c.id === id);
        if (!conv || !els?.messages) return;

        els.messages.innerHTML = '';
        if (els.hint) els.hint.style.display = conv.messages.length ? 'none' : '';

        for (const m of conv.messages) {
            if (m.role === 'user') {
                const div = document.createElement('div');
                div.className = 'msg user';
                div.textContent = m.text;
                els.messages.appendChild(div);
            } else {
                const div = document.createElement('div');
                div.className = 'msg bot';

                const textEl = document.createElement('div');
                textEl.className = 'msg-text';
                textEl.textContent = m.text || '';

                const metaEl = document.createElement('div');
                metaEl.className = 'msg-meta';
                (async () => {
                    const modelName = await ModelInfo.loadModelInfoOnce();
                    metaEl.textContent = `Response generated by ${modelName}.`;
                })();

                div.appendChild(textEl);
                div.appendChild(metaEl);
                els.messages.appendChild(div);
            }
        }

        if (conv.framesMeta && conv.framesMeta.length) {
            const botBubbles = els.messages.querySelectorAll('.msg.bot');
            const lastBot = botBubbles.length ? botBubbles[botBubbles.length - 1] : null;
            if (lastBot) FrameRenderer.renderFramesInsideBubble(lastBot, conv.framesMeta);
        }

        els.messages.scrollTop = els.messages.scrollHeight;
    }

    /*
     * Appends a single message to the chat and auto-scrolls to bottom
     */
    function appendMessage(text, who /* 'user' | 'bot' */) {
        const div = document.createElement('div');
        div.className = `msg ${who}`;

        if (who === 'bot') {
            const textEl = document.createElement('div');
            textEl.className = 'msg-text';
            textEl.textContent = text || '';

            const metaEl = document.createElement('div');
            metaEl.className = 'msg-meta';
            metaEl.textContent = ' ';

            div.appendChild(textEl);
            div.appendChild(metaEl);
        } else {
            div.textContent = text || '';
        }

        els.messages?.appendChild(div);
        if (els.messages) els.messages.scrollTop = els.messages.scrollHeight;
        return div;
    }

    return {
        attach,
        renderConvList,
        renderConversation,
        appendMessage,
        updateNewChatButtonVisibility
    };
})();