/**
 * UI wiring: composer lock/unlock, events, streaming, delete confirm, new chat
 */
const ChatUI = (function () {
    let els = null;
    let currentController = null;

    /*
     * Disables input and send button to prevent new messages
     */
    function lockComposer() {
        if (!els?.composer) return;
        els.composer.classList.add('is-locked');
        if (els.input) {
            els.input.disabled = true;
            els.input.setAttribute('aria-disabled', 'true');
        }
        if (els.sendBtn) {
            els.sendBtn.disabled = true;
            els.sendBtn.setAttribute('aria-disabled', 'true');
        }
    }

    /*
     * Enables input and send button, clears input field
     */
    function unlockComposer() {
        if (!els?.composer) return;
        els.composer.classList.remove('is-locked');
        if (els.input) {
            els.input.disabled = false;
            els.input.removeAttribute('aria-disabled');
            els.input.value = '';
            els.input.style.height = 'auto';
        }
        if (els.sendBtn) {
            els.sendBtn.disabled = false;
            els.sendBtn.removeAttribute('aria-disabled');
        }
    }

    /*
     * Sets busy state for input controls during processing
     */
    function setBusy(busy) {
        if (els.sendBtn) els.sendBtn.disabled = busy;
        if (els.input) els.input.disabled = busy;
    }

    /*
     * Auto-resizes textarea based on content up to max height
     */
    function autoGrow() {
        if (!els?.input) return;
        els.input.style.height = 'auto';
        els.input.style.height = Math.min(els.input.scrollHeight, 200) + 'px';
    }

    /*
     * Streams chat response from API and updates UI in real-time
     */
    async function streamChat(userText) {
        if (currentController) currentController.abort();
        currentController = new AbortController();

        const botDiv = ChatRenderer.appendMessage('', 'bot');
        const botTextEl = botDiv.querySelector('.msg-text');
        const botMetaEl = botDiv.querySelector('.msg-meta');

        let fullBotText = '';
        let framesMeta = null;

        try {
            const res = await fetch('/api/chat', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Accept': 'text/event-stream'
                },
                body: JSON.stringify({ input: userText }),
                signal: currentController.signal
            });

            if (!res.ok || !res.body) {
                throw new Error(`HTTP ${res.status} ${res.statusText}`);
            }

            const reader = res.body.getReader();
            const decoder = new TextDecoder('utf-8');

            const sse = SSEUtil.createStrictSSEReader(({ event, data }) => {
                if (data === '[DONE]') return;

                if (event === 'frame') {
                    try { framesMeta = JSON.parse(data); } catch { }
                    return;
                }

                const text = SSEUtil.extractText(data);
                if (!text) return;

                const prev = botTextEl.textContent || '';
                let chunk = text;

                // collapse double-whitespace at chunk boundary
                if (/\s$/.test(prev) && /^\s/.test(chunk)) {
                    chunk = chunk.replace(/^\s+/, ' ');
                }

                botTextEl.textContent += chunk;
                fullBotText += chunk;

                if (els.messages) els.messages.scrollTop = els.messages.scrollHeight;
            });

            while (true) {
                const { value, done } = await reader.read();
                if (done) break;
                sse.feed(decoder.decode(value, { stream: true }));
            }
            sse.flush();

            const modelName = await ModelInfo.loadModelInfoOnce();
            if (botMetaEl) {
                botMetaEl.textContent = `Response generated by ${modelName}.`;
            }

            return { botText: fullBotText, framesMeta, botBubble: botDiv };
        } finally {
            currentController = null;
        }
    }

    /*
     * Starts a new conversation by clearing active state and UI
     */
    function startNewChat() {
        // Clear activeId: next message will create a new conversation
        const s = ConversationState.getState();
        s.activeId = null;
        ConversationState.persist();

        // Clear UI
        if (els.messages) els.messages.innerHTML = '';
        if (els.hint) els.hint.style.display = '';
        if (els.input) {
            els.input.value = '';
            els.input.style.height = 'auto';
        }

        unlockComposer();
        ChatRenderer.renderConvList();
        ChatRenderer.updateNewChatButtonVisibility();
    }

    /*
     * Deletes conversation and updates UI without confirmation
     */
    function deleteConversationNoConfirm(id) {
        ConversationState.deleteConversation(id);
        ChatRenderer.renderConvList();
        ChatRenderer.updateNewChatButtonVisibility();

        const st = ConversationState.getState();
        if (st.activeId) {
            ChatRenderer.renderConversation(st.activeId);
            const conv = ConversationState.getActiveConversation();
            if (conv && conv.messages.length > 0) lockComposer(); else unlockComposer();
        } else {
            if (els.messages) els.messages.innerHTML = '';
            if (els.hint) els.hint.style.display = '';
            unlockComposer();
        }
    }

    /*
     * Shows inline confirmation dialog for conversation deletion
     */
    function showInlineConfirm(li) {
        document.querySelectorAll('.confirm-chip').forEach(c => c.remove());
        const chip = document.createElement('span');
        chip.className = 'confirm-chip';
        chip.innerHTML = `
    <span>Delete?</span>
    <button type="button" class="btn-confirm-yes danger">Delete</button>
    <button type="button" class="btn-confirm-no">Cancel</button>
  `;
        li.appendChild(chip);

        chip.querySelector('.btn-confirm-yes').addEventListener('click', (ev) => {
            ev.stopPropagation();
            deleteConversationNoConfirm(li.dataset.id);
            chip.remove();
        });

        chip.querySelector('.btn-confirm-no').addEventListener('click', (ev) => {
            ev.stopPropagation();
            chip.remove();
        });
    }

    /*
     * Initializes UI with event listeners and renders initial state
     */
    function init(_els) {
        els = _els;

        // Attach to renderer
        ChatRenderer.attach(els);

        // Key events
        els.input?.addEventListener('input', autoGrow);
        window.addEventListener('resize', autoGrow);
        autoGrow();

        // Submit on Enter (Shift+Enter = newline)
        els.input?.addEventListener('keydown', (e) => {
            if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                els.composer?.requestSubmit();
            }
        });

        // Initial paint
        ChatRenderer.renderConvList();
        const st = ConversationState.getState();
        if (st.activeId) {
            ChatRenderer.renderConversation(st.activeId);
            ChatRenderer.updateNewChatButtonVisibility();
            const conv = ConversationState.getActiveConversation();
            if (conv && conv.messages.length > 0) lockComposer(); else unlockComposer();
        } else {
            unlockComposer();
        }

        // Preload model info (non-blocking)
        ModelInfo.loadModelInfoOnce();

        // Composer submit (single-turn)
        els.composer?.addEventListener('submit', async (e) => {
            e.preventDefault();
            if (els.composer?.classList.contains('is-locked')) return;

            const text = (els.input?.value || '').trim();
            if (!text) return;

            ConversationState.ensureActiveConversation(text);

            if (els.hint) els.hint.style.display = 'none';

            ChatRenderer.appendMessage(text, 'user');
            ConversationState.addMessageToActive('user', text);

            els.input.value = '';
            autoGrow();

            try {
                setBusy(true);
                const { botText, framesMeta, botBubble } = await streamChat(text);

                if (botText) ConversationState.addMessageToActive('bot', botText);
                if (framesMeta) ConversationState.setFramesMetaForActive(framesMeta);

                if (framesMeta && botBubble) {
                    await FrameRenderer.renderFramesInsideBubble(
                        botBubble.querySelector('.msg-text')?.parentElement || botBubble,
                        framesMeta
                    );
                }

                ConversationState.bumpActiveToTop();
                ChatRenderer.renderConvList();

                // single-turn lock
                lockComposer();

            } catch (err) {
                console.error(err);
                ChatRenderer.appendMessage('Sorry, something went wrong.', 'bot');
                ConversationState.addMessageToActive('bot', 'Sorry, something went wrong.');
            } finally {
                setBusy(false);
            }
        });

        // New chat button
        els.newChatBtn?.addEventListener('click', startNewChat);

        // Conv list interactions (select or delete)
        els.convList?.addEventListener('click', (e) => {
            const delBtn = e.target.closest('.delete-chat');
            const li = e.target.closest('.conv-item');

            if (delBtn && li) {
                e.stopPropagation();
                showInlineConfirm(li);
                return;
            }

            if (li) {
                const id = li.dataset.id;
                const ok = ConversationState.setActive(id);
                if (!ok) return;
                ChatRenderer.renderConvList();
                ChatRenderer.renderConversation(id);

                const conv = ConversationState.getState().conversations.find(c => c.id === id);
                if (conv && conv.messages && conv.messages.length > 0) {
                    lockComposer();
                } else {
                    unlockComposer();
                }
            }
        });
    }

    return {
        init,
        lockComposer,
        unlockComposer,
        startNewChat
    };
})();