# Logging
logging:
  level: INFO                          # DEBUG | INFO | WARNING | ERROR | CRITICAL
  format: "%(asctime)s %(levelname)-7s %(name)s — %(message)s"
  file: null                           # path to enable rotating file log

# Metrics
metrics:
  enabled: false
  export_interval_s: 5.0
  prometheus:
    enabled: false
    port: 8000

# NOTE: You can use your own model and video of your choice. To use the example pallet defect detection model and warehouse video, download and extract them with:
#       wget -O pallet_defect_detection.zip "https://github.com/open-edge-platform/edge-ai-resources/raw/06bb0d621cb14a1791672552a538beddddcc4066/models/INT8/pallet_defect_detection.zip" ; Expand-Archive -Path "pallet_defect_detection.zip" -DestinationPath "models"
#       wget -O warehouse.avi "https://github.com/open-edge-platform/edge-ai-resources/raw/c13b8dbf23d514c2667d39b66615bd1400cb889d/videos/warehouse.avi"

# ---------------- For Advanced Users Only --------------------
# Replace C:/Users/path/to/video.avi and C:/Users/path/to/detection/model.xml with your downloaded/own paths
# When using whipclientsink, the WHIP endpoint path must include the /whip suffix (e.g. http://localhost:8889/front/whip). To view the stream in a browser, open http://localhost:8889/front (without /whip).
raw_pipelines:
  front: "" #"filesrc location=\"C:/Users/path/to/video.avi\" ! decodebin3 name=src ! gvadetect model=\"C:/Users/path/to/detection/model.xml\" device=GPU pre-process-backend=d3d11 name=detection model-instance-id=inst0 threshold=0.4 batch-size=1 ! queue ! gvawatermark ! d3d11convert ! gvafpscounter  ! d3d11videosink name=sink"
  back: "" #"filesrc location=\"C:/Users/path/to/video.avi\" ! decodebin3 name=src ! gvadetect model=\"C:/Users/path/to/detection/model.xml\" device=GPU pre-process-backend=d3d11 name=detection model-instance-id=inst0 threshold=0.4 batch-size=1 ! queue ! gvawatermark ! d3d11convert ! gvafpscounter  ! identity name=sink ! mfh264enc bitrate=2000 gop-size=15 ! h264parse ! rtspclientsink location=rtsp://localhost:8554/back"
  right: "" #"filesrc location=\"C:/Users/path/to/video.avi\" ! decodebin3 name=src ! gvadetect model=\"C:/Users/path/to/detection/model.xml\" device=GPU pre-process-backend=d3d11 name=detection model-instance-id=inst0 threshold=0.4 batch-size=1 ! queue ! gvawatermark ! d3d11convert ! gvafpscounter ! identity name=sink ! mfh264enc bitrate=2000 gop-size=15 ! h264parse ! whipclientsink signaller::whip-endpoint=http://localhost:8889/front/whip"
  left: "" #"filesrc location=\"C:/Users/path/to/video.avi\" ! decodebin3 name=src ! gvadetect model=\"C:/Users/path/to/detection/model.xml\" device=GPU pre-process-backend=d3d11 name=detection model-instance-id=inst0 threshold=0.4 batch-size=1 ! queue ! gvametaconvert add-empty-results=true ! gvametapublish method=mqtt topic=inference/back address=tcp://localhost:1883 ! queue ! gvawatermark ! d3d11convert ! gvafpscounter ! d3d11videosink name=sink"
  camera: "" #"gencamsrc serial=12345678 pixel-format=mono8 name=src ! videoscale ! video/x-raw, width=1920,height=1080 ! videoconvert ! queue ! d3d12videosink name=sink"
  
#--------------------------------------------------------------
#--------------------------------------------------------------

#----------------- Basic Configuration Steps --------------------
# Models
models:
  inst0:
    type: detection                    # detection | classification
    model: "C:/Users/path/to/detection/model.xml"  # replace with your downloaded/own model path
    device: GPU                        # CPU | GPU | NPU
    properties:
      batch_size: 1
      threshold: 0.4
  inst1:
    type: classification
    model: "C:/Users/path/to/classification/model.xml"  # replace with your downloaded/own model path
    device: GPU
    properties:
      batch_size: 4

# Pipelines
pipelines:
  front:
    input:
      type: file                             # file
      url: "C:/Users/path/to/video.avi"          # replace with your downloaded/own video path
      #type: rtsp                            # rtsp
      #url: "rtsp://<ip>:<port>/live.sdp"    # add video path
      #type: camera                          # camera
      #serial: 1234567                       # add camera serial number
      #pixel-format: mono8                   # add camera pixel format (e.g. mono8, bgr8, etc.)
      #width: 1280                           # add camera width
      #height: 720                           # add camera height              
    inference:
      model_id: inst0
    output:
      frame:                          
        - type: webrtc                   # webrtc 
          peer_id: front                 # http://localhost:8889/front 
        #- type: rtsp                    # rtsp
        #  path: /front                  # rtsp://localhost:8554/front 
      metadata:
        #- type: mqtt
        #  topic: inference/front
        #  port: 1883
        - type: file
          path: "output/front-inference.jsonl"
  back:
    input:
      type: file
      url: "C:/Users/path/to/video.avi"          # replace with your downloaded/own video path
    inference:
      model_id: inst0
    output:
      frame: 
        - type: webrtc                   # webrtc 
          peer_id: back                  # http://localhost:8889/back 
        #- type: rtsp                    # rtsp
        #  path: /back                   # rtsp://localhost:8554/back 
      metadata:
        #- type: mqtt
        #  topic: inference/back
        #  port: 1883
        - type: file
          path: "output/back-inference.jsonl"
  